#!/bin/bash

file_path=$(realpath $0)
script_path=$(dirname $file_path)
tool_path=$(dirname $script_path)

# read conf
source $tool_path/conf/env.conf

log_stor_path=$1
time_stamp=`date +"%Y%m%d%H%M%S"`

if [ -d $log_stor_path ];then
    #stor cluster log
    for ip in "${manage_ips[@]}"; do
        echo  "[INFO]$ip stor log in $log_stor_path/$time_stamp"
        sshpass -p $passwd ssh $user@$ip "mkdir -p $log_stor_path/$time_stamp"
        sshpass -p $passwd ssh $user@$ip "cp -r /var/log/storage $log_stor_path/$time_stamp"
        sshpass -p $passwd ssh $user@$ip "cp -r /var/log/messages $log_stor_path/$time_stamp"
        echo "[INFO]$ip log stor success"
    done
    for ip in "${client_manage_ips[@]}"; do
        echo  "[INFO]$ip stor log in $log_stor_path/$time_stamp"
        sshpass -p $passwd ssh $user@$ip "mkdir -p $log_stor_path/$time_stamp"
        sshpass -p $passwd ssh $user@$ip "cp -r /var/log/storage $log_stor_path/$time_stamp"
        sshpass -p $passwd ssh $user@$ip "cp -r /var/log/messages $log_stor_path/$time_stamp"
        echo "[INFO]$ip log stor success"
    done

else
    echo "[ERROR]log stor path invalid"
fi


