#!/bin/bash
file_path=$(realpath $0)
script_path=$(dirname $file_path)
tool_path=$(dirname $script_path)

# read conf
source $tool_path/conf/env.conf

if [ $2 == "show" ]; then
    for ip in "${manage_ips[@]}"; do
        sshpass -p $passwd ssh $user@$ip "onestor dpe show fault_inject | grep $1"
        echo "[INFO]$ip fault inject $1 $2 success."
    done

elif [[ $2 == "on" || $2 == "off" ]]; then
    for ip in "${manage_ips[@]}"; do
        sshpass -p $passwd ssh $user@$ip "onestor dpe set fault_inject index $1 switch $2"
        echo "[INFO]$ip fault inject $1 $2 success."
    done
else
    echo "[ERROR]Invalid Parameter."
fi
