#!/bin/bash


file_path=$(realpath $0)
script_path=$(dirname $file_path)
tool_path=$(dirname $script_path)

# read conf
source $tool_path/conf/env.conf



# clear all core
for ip in "${manage_ips[@]}"; do
    echo "[INFO]Clear coredump file in $ip."
    sshpass -p $passwd ssh $user@$ip "rm -rf /var/lib/systemd/coredump/*"
done

for ip in "${client_manage_ips[@]}"; do
    echo "[INFO]Clear coredump file in $ip."
    sshpass -p $passwd ssh $user@$ip "rm -rf /var/lib/systemd/coredump/*"
done


